# LuCI LiteBike Application Makefile
# Copyright (C) 2026 LiteBike Project

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LiteBike Integrated Proxy Server
LUCI_DEPENDS:=+litebike +luci-compat +luci-lib-jsonc
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
